# Generated by Django 3.0.8 on 2020-08-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200802_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filt_p',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='filt_c',
            field=models.FloatField(null=True),
        ),
    ]
