# Generated by Django 3.0.8 on 2020-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200803_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
