# Generated by Django 3.0.8 on 2020-08-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seller_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='gender',
        ),
    ]
